[model]
model = "mistral-small"  # Update the model name here
enable_multi_modal = false
ollama_server_url = "https://api.mistral.ai"  # Update the URL here

[sample_prompts]
prompts = [
  "meme image with trending topics"
]

[environment]
type = "dev"

[timeout]
llm = 30

[target_agent_id]
model = "mistral-small"  # Update the model name here
timeout = 15
environment = "dev"
enable_multi_modal = false
ollama_server_url = "https://api.mistral.ai"
sample_prompts = [
  "design a meme with the trends", 
  "design a meme based on the trending topics" 
]
